# Generated by Django 2.0.1 on 2018-02-03 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inno_lib', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inno_lib.Document')),
                ('editor', models.CharField(max_length=100)),
                ('journal', models.CharField(max_length=100)),
            ],
            bases=('inno_lib.document',),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inno_lib.Document')),
                ('publisher', models.CharField(max_length=100)),
            ],
            bases=('inno_lib.document',),
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.AddField(
            model_name='documentinstance',
            name='borrower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='documentinstance',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this book for the whole lib', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='documentinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('m', 'Maintenance'), ('o', 'On loan'), ('a', 'Available'), ('r', 'Reserved')], default='m', help_text='Document availability', max_length=1),
        ),
    ]
