version: '3'
services:
  db:
    image: postgres
    restart: always
    volumes:
      - ../postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 'test'
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ..:/libinno
    command: python manage.py runserver 0.0.0.0:8000

